language: go
services:
- docker
go:
- 1.8
addons:
  apt:
    packages:
    - upx-ucl
# before_install:
#   - go get github.com/mattn/goveralls
install:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure
script:
- make release
- upx bin/prometheus-used-metrics
# - $HOME/gopath/bin/goveralls -service=travis-ci
# after_deploy:
# - make docker VERSION=$TRAVIS_TAG
# - docker login -u $DOCKER_USER -p $DOCKER_PASS
# - export REPO=mattdeboer/prometheus-used-metrics
# - docker push $REPO:$TRAVIS_TAG
# - docker push $REPO:${TRAVIS_TAG}-alpine
# - docker tag $REPO:$TRAVIS_TAG $REPO:latest
# - docker push $REPO:latest
